baseURL = 'https://showlahossain.github.io'
languageCode = 'en-us'
theme = 'paper'
[params.profileMode]
title = 'Showla Hossain'
imageUrl = "photo.jpeg"
imageTitle = "Trina"
imageWidth = 160
imageHeight = 160
enabled = true
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false