baseURL = 'https://showlahossain.github.io/'
languageCode = 'en-us'
theme = 'paper'
disableThemeToggle = true
[params.profileMode]
title = 'Showla Hossain'
imageUrl = "photo.jpg"
imageTitle = "Trina"
imageWidth = 160
imageHeight = 160
enabled = true


  [[params.profileMode.buttons]]
  name = "Nutratology"
  url = "https://www.nutratology.com?ref=SHOWLA10"
  
  [[params.profileMode.buttons]]
  name = "Elite Time"
  url = "https://yehielstory.com/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
